#!/bin/bash
set -e

# Output directory
OUTPUT=pdf
# PDF name (without extension)
PDF_NAME=thesis
# packages path
PACKAGES=settings/packages.tex
# PSL template directory
PSL_TEMPLATE=psl

# Create the pdf directory if it doesn't exist
if [ ! -d "$OUTPUT" ]; then
  mkdir "$OUTPUT"
fi
if [ ! -d "$PSL_TEMPLATE/$OUTPUT" ]; then
  mkdir "$PSL_TEMPLATE/$OUTPUT"
fi

## do thesis.tex

# Comment out \drafttrue for final compilation
sed -i '' 's@\\drafttrue@% \\drafttrue@g' "$PACKAGES"

pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
# Compile nomenclature
makeindex "$OUTPUT/$PDF_NAME.nlo" -s nomencl.ist -o "$OUTPUT/$PDF_NAME.nls"
# Compile index
makeindex "$OUTPUT/$PDF_NAME"
# Compile bibliography
biber "$OUTPUT/$PDF_NAME"
pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
# Compile glossary
cd "$OUTPUT"
makeglossaries "$PDF_NAME"
cd ..
pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"

# Uncomment \drafttrue for draft compilation
sed -i '' 's@% \\drafttrue@\\drafttrue@g' "$PACKAGES"

## do psl/thesis.tex

cd "$PSL_TEMPLATE"
pdflatex -interaction=nonstopmode --output-directory="$OUTPUT" "$PDF_NAME"
pdflatex -interaction=nonstopmode --output-directory="$OUTPUT" "$PDF_NAME"
pdflatex -interaction=nonstopmode --output-directory="$OUTPUT" "$PDF_NAME"
cd ..

# merge the two
pdftk psl/pdf/thesis.pdf cat 1 output pdf/psl-first.pdf
pdftk pdf/thesis.pdf cat 2-end output pdf/thesis-tail.pdf
pdftk pdf/psl-first.pdf pdf/thesis-tail.pdf cat output pdf/thesis.pdf
