#!/bin/bash
set -e

# Output directory
OUTPUT=pdf
# PDF name (without extension)
PDF_NAME=thesis
# packages path
PACKAGES=settings/packages.tex
# PSL template directory
# PSL_TEMPLATE=psl

# Create the pdf directory if it doesn't exist
if [ ! -d "$OUTPUT" ]; then
  mkdir "$OUTPUT"
fi
# if [ ! -d "$PSL_TEMPLATE/$OUTPUT" ]; then
#   mkdir "$PSL_TEMPLATE/$OUTPUT"
# fi

# Clean the output directory
# rm -rf "$OUTPUT"/*

## do thesis.tex

# Comment out \drafttrue for final compilation
# sed -i.bak 's/\\drafttrue/%\\drafttrue/g' "$PACKAGES"

pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
echo "Finished first compilation"
# Compile nomenclature
makeindex "$OUTPUT/$PDF_NAME.nlo" -s nomencl.ist -o "$OUTPUT/$PDF_NAME.nls"
echo "Finished nomenclature"
# Compile index
makeindex "$OUTPUT/$PDF_NAME"
echo "Finished index"
# Compile bibliography
biber "$OUTPUT/$PDF_NAME"
echo "Finished bibliography"
pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
echo "Finished second compilation"
# Compile glossary
cd "$OUTPUT"
makeglossaries "$PDF_NAME"
echo "Finished glossary"
cd ..
pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
echo "Finished third compilation"
pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
echo "Finished fourth compilation"

# Uncomment \drafttrue for draft compilation
# sed -i.bak 's/%\\drafttrue/\\drafttrue/g' "$PACKAGES"

## do psl/thesis.tex

# cd "$PSL_TEMPLATE"
# pdflatex -interaction=nonstopmode --output-directory="$OUTPUT" "$PDF_NAME"
# pdflatex -interaction=nonstopmode --output-directory="$OUTPUT" "$PDF_NAME"
# pdflatex -interaction=nonstopmode --output-directory="$OUTPUT" "$PDF_NAME"
# cd ..

# merge the two
pdftk pdf/thesis.pdf cat 2-end output pdf/thesis-tail.pdf
pdftk psl-first.pdf pdf/thesis-tail.pdf cat output pdf/thesis.pdf
echo "Finished merging"
