#!/bin/bash
set -e

# Output directory
OUTPUT=pdf
# PDF name (without extension)
PDF_NAME=thesis

# Create the pdf directory if it doesn't exist
if [ ! -d "$OUTPUT" ]; then
  mkdir "$OUTPUT"
fi

pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"
