#!/bin/bash
set -e

# Output directory
OUTPUT=pdf
# PDF name (without extension)
PDF_NAME=thesis

# Create the pdf directory if it doesn't exist
if [ ! -d "$OUTPUT" ]; then
  mkdir "$OUTPUT"
fi

pdflatex -interaction=nonstopmode --synctex=1 --output-directory="$OUTPUT" -file-line-error "$PDF_NAME"

# merge the two
# pdftk pdf/thesis.pdf cat 2-end output pdf/thesis-tail.pdf
# pdftk psl-first.pdf pdf/thesis-tail.pdf cat output pdf/thesis-but-last.pdf
# pdftk pdf/thesis-but-last.pdf psl-last.pdf cat output pdf/thesis.pdf
# echo "Finished merging"
